added logging to CI

diff --git a/run b/run
--- a/run
+++ b/run
@@ -109,7 +109,10 @@ all_tests() {
     python3 -m coverage report >> "$LOG_FILE" 2>> "$ERROR_LOG_FILE"
 
     echo 'Running API tests...'
-    if ! newman run tests/BoilerMatch.postman_collection.json --environment tests/BoilerMatch.postman_environment.json --reporters cli,junit --reporter-junit-export newman-report.xml >> "$LOG_FILE" 2>> "$ERROR_LOG_FILE"; then
+    if ! newman run tests/BoilerMatch.postman_collection.json \
+        --environment tests/BoilerMatch.postman_environment.json \
+        --reporters cli,junit --reporter-junit-export newman-report.xml \
+        >> "$LOG_FILE" 2>> "$ERROR_LOG_FILE"; then
         echo "Error running API tests"
         return 1
     fi
